### ISSUE TITLE
Layout fullWidth - is it meant to be full width of screen or container?

### ISSUE THREAD

**Issue by intellix** [QwikDev/qwik-image#7]
So we've just migrated from **@unpic/qwik** due to the transformers/detectors and API being MUCH better here in qwik-image where I can literally just pass a switch statement and tell it how to transform URLs.

One issue I've just noticed is that our frontend was using a lot of layout="fullWidth" and now I'm noticing a lot of image requests of 3840 width (double my screen width on a MBP M1 2021).

When I look at the documentation between the two libraries, this is how that property is described:

- qwik-image (https://github.com/qwikifiers/qwik-image#fullwidth): the width of the image is always equal to the width of the screen
- unpic/qwik (https://unpic.pics/img/qwik): the image will be rendered at full width of its container. This is optimized for full-width hero images. You can set height to a fixed value, which will mean the image will be rendered at that fixed height and scale horizontally to fill the container.

I can see that Gatsby behaviour is similar to qwik-image: https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-plugin-image/

Also, I see that unpic/react works the same as qwik-image (https://unpic.pics/img/learn/#layouts): 
> The fullWidth layout will stretch to the width of the screen, and is best for hero images and banners. Fixed images don’t scale at all, and are best for logos and icons.

I'm thinking that the way that it works for unpic/qwik is more useful than the functionality provided by qwik-image where it just uses 100% of the screen width as you're often trying to fill containers with images and want some help sizing them up depending on what's available.

**Comment by gioboa** [comment]
Thanks @intellix for sharing, if you have any feedback / needs please let me know. More then welcome to help you.
