### ISSUE TITLE
feat: Automatic optimisation of local images

### ISSUE THREAD

**Issue by intellix** [QwikDev/qwik-image#8]
We're using qwik-image as a way of replacing image paths with optimised versions based on their SRC using transformers. It's nice and simple:

```ts
export const imageTransformer$ = $(imageTransformer);

export function imageTransformer({ src, width }: ImageTransformerProps): string {
  switch (true) {
    case src.startsWith('https://static.'):
    case src.startsWith('https://static-dev.'): {
      return cloudflareTransformer({ src, width });
    }
    case src.startsWith('https://imgix.'): {
      return imgixTransformer({ src, width });
    }
    default: {
      return src;
    }
  }
}
```

Now we import from qwik-image to automatically optimise stuff:
```ts
import { Image } from 'qwik-image';

<Image src='https://somewhere.com/image.jpeg' width={100}>
```

This is great, but I've noticed that now none of the images within the repository itself are being optimised, because the paths are relative: `/assets/banner.jpeg`.

Looking at the qwik docs, I can see that vite-imagetools can be used to optimise images at build time by using a ?jsx suffix:
```ts
import Image from '/assets/banner.jpeg?jsx';
```

So with the above, I know that if I have dynamic/absolute paths I can use qwik-image and if they're local, I can use the JSX import suffix to automatically optimise them during the build process.

My problem with this, is that the frontend developer needs to know which one to use in which scenario and I feel like most developers just don't care and the internet/performance is basically magic. 

In order to make it automatic and to only use qwik-image my plan was to check the current URL and prefix relative image paths (which has Cloudflare in front of it when deployed outside of localhost) and then optimise those like so:

```ts
export function createImageTransformer(url: URL) {
  return ({ src, width }: ImageTransformerProps) => {
    if (src.startsWith('/') && url.host !== 'localhost') {
      src = `https://${url.host}${src}`;
    }

    switch (true) {
      case src.startsWith(`https://${url.host}`):
      case src.startsWith('https://static.'):
      case src.startsWith('https://static-dev.'): {
        return cloudflareTransformer({ src, width });
      }
      ...
  }
}

export default component$(() => {
  const loc = useLocation();
  useImageProvider({ imageTransformer$: $(createImageTransformer(loc.url)) });
  ...
}
```

But I can't seem to pass in a value from useLocation to the imageTransformer$ QRL Function that is created dynamically:
```
Qrl($) scope is not a function, but it's capturing local identifiers: imageTransformer
```

Is it possible to automatically use vite-imagetools somehow within qwik-image, or is it possible to do something like the above?

**Comment by gioboa** [comment]
Yep, an alternative solution cloud be implement you own Vite plugin with vite-imagetools and take inspiration from the official one.
[Here is the code](https://github.com/BuilderIO/qwik/blob/58b01ef26cf2f02d566d5154b50b433db77a313e/packages/qwik-city/buildtime/vite/image-jsx.ts#L11)

**Comment by gioboa** [comment]
@intellix Can we close this one?
